const profiles = [
    {
      id: 1,
      name: 'Alvin Estado',
      role: 'Backend Developer',
      location: 'Sydney, AU',
      skills: ['Python', 'Django', 'PostgreSQL'],
      image: './public/assets/alvin_estado.jpeg', // Make sure the image path matches your project structure
    },
    {
      id: 2,
      name: 'Cameron Beattie',
      role: 'Backend Developer',
      location: 'Sydney, AU',
      skills: ['React', 'Tailwind CSS', 'GraphQL'],
      image: './public/assets/cameron_beattie.jpeg',
    },
    {
      id: 3,
      name: 'Tinaika Pereira',
      role: 'Full-Stack Developer',
      location: 'Sydney, AU',
      skills: ['Node.js', 'Express', 'MongoDB'],
      image: './public/assets/tinaika_pereira.jpeg',
    },
    {
      id: 4,
      name: 'Kate Stapley',
      role: 'Frontend Developer',
      location: 'Sydney, AU',
      skills: ['HTML', 'CSS', 'JavaScript', 'Node.js'],
      image: './public/assets/kate_stapley.jpeg',
    },
    {
        id: 5,
        name: 'Alex Sexwale',
        role: 'Head of Development',
        location: 'Cape Town, SA',
        skills: ['Tech Lead', 'Tailwind CSS', 'Node.js', 'React.js', 'Jest', 'mySQL', 'MongoDB'],
        image: './public/assets/alex_sexwale.jpeg',
      },
      {
        id: 6,
        name: 'Tristan Kennedy',
        role: 'Software Engineer',
        location: 'Melbourne, AU',
        skills: ['Scrum Master', 'Laravel', 'React.js', 'Jest', 'PHPunit', 'Docker'],
        image: './public/assets/tristan_kennedy.jpeg',
      },
      {
        id: 7,
        name: 'Kevin Vongmany',
        role: 'Full-Stack Developer',
        location: 'Adelaide, AU',
        skills: ['HTML', 'CSS', 'JavaScript', 'Node.js'],
        image: './public/assets/kevin_vongmany.jpeg',
      },
      {
        id: 8,
        name: 'Wendy Xiao',
        role: 'Backend Developer',
        location: 'Sydney, AU',
        skills: ['HTML', 'CSS', 'JavaScript', 'Node.js'],
        image: './public/assets/wendy_xiao.jpeg',
      },
      {
        id: 9,
        name: 'June Li',
        role: 'Backend Developer',
        location: 'Sydney, AU',
        skills: ['HTML', 'CSS', 'JavaScript', 'Node.js'],
        image: './public/assets/june_li.jpeg',
      },
      {
        id: 10,
        name: 'Benjamin Rice',
        role: 'Fullstack Developer',
        location: 'Sydney, AU',
        skills: ['HTML', 'CSS', 'JavaScript', 'Node.js'],
        image: './public/assets/benjamin_rice.jpeg',
      },
      {
        id: 11,
        name: 'Sam Doe',
        role: 'Fullstack Developer',
        location: 'Sydney, AU',
        skills: ['HTML', 'CSS', 'JavaScript', 'Node.js'],
        image: './public/assets/user.JPG',
      },
  ];
  
  module.exports = profiles; // Export the profiles array